### ISSUE TITLE
mozMeetup Octubre

### ISSUE THREAD

**Issue by ccarruitero** [mozillaperu/meetups#1]
## Como proponer una charla?
1. [Abre un issue](https://github.com/mozillaperu/meetups/issues/new/choose) y completa los detalles de tu charla.
2. Espera que se inicie una conversación sobre tu propuesta y opcionalmente haz cambios a tu propuesta original.
3. Al termino de la fecha limite para presentar propuestas, se realizará una votación utilizando github reactions, para ello agregaremos cada charla elegible en este issue a manera de comentario, las charlas con mayor cantidad de reacciones positivas serán las elegidas para el siguiente meetup.
 
**Nota:**
Las charlas propuestas deben estar relacionadas de alguna forma a la [misión de Mozilla](https://www.mozilla.org/es-ES/about/manifesto/) y/o alguno de los proyectos que inició o mantiene. Desde tecnologías y herramientas creadas y/o utilizadas hasta proyectos de la comunidad.

Puedes encontrar una lista de temas que podrían resultar interesantes para alguna charla desde [aquí](https://github.com/mozillaperu/meetups/labels/idea).

## Como agregar nuevas ideas?
Para agregar alguna idea, sólo debes abrir un nuevo issue y agregarle el _label "idea"_.

No es necesario tener una idea muy desarrollada o completar todo el ``template``, sino más bien iniciar la conversación respecto al tema y a través de ello conseguir alguna idea concreta para alguna charla.
Si necesitas ayuda con el proceso, no dudes en contactarnos a través de [Twitter](https://twitter.com/mozillaperu) o [Facebook](https://www.facebook.com/MozillaPeru/).

**Comment by miguelAliaga** [comment]
la lista de charlas anteriores esta vacia ,https://github.com/mozillaperu/meetups/labels/idea

**Comment by lupomontero** [comment]
Mi propuesta: https://github.com/mozillaperu/meetups/issues/3 :blush:
