### ISSUE TITLE
Propuesta de charla: MediaDevices, MediaStream y MediaRecorder

### ISSUE THREAD

**Issue by lupomontero** [mozillaperu/meetups#12]
¡Hola!

Mi nombre es Lupo Montero. Trabajo en [Laboratoria](https://www.laboratoria.la/).

Me contactan por ([Twitter](https://twitter.com/lupomontero) / [GitHub](https://github.com/lupomontero/))

**Título de la charla**

MediaDevices, MediaStream y MediaRecorder

**Tipo de presentación que quiero hacer**

- [x] Keynote (20 a 30 minutos)

**Descripción de la charla**

En esta charla veremos cómo, con APIs nativas del navegador, podemos acceder a streams de video (cámara, pantalla, ventana, ...) y audio (micro) con [`MediaDevices`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices), combinarlos usando [`MediaStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream), componer imágenes en un [`canvas`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement), y grabar el resultado en un archivo de video usando [`MediaRecorder`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder).

**Comment by lupomontero** [comment]
@AngelFQC, queda entonces confirmada esta charla para el jueves?

**Comment by AngelFQC** [comment]
Sí, confirmada :)
