### ISSUE TITLE
Propuesta de charla: Introducción a Indieweb

### ISSUE THREAD

**Issue by jjdelc** [mozillaperu/meetups#17]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación |  Yo 
| Tipo de presentación       | Exposición

¡Hola!
Soy Jj, Trabajo en Crunch.io, me pueden encontrar en https://www.isgeek.net/ 
 
**Intro a Indieweb**

Introducir el concepto de Indieweb y explicar los conceptos principales necesarios para que cada uno pueda participar. Hablando de protocolos tomo Micropub, Pose, Pesos, syndication, indieauth, silos. Y como llevar una vida "social" sin depender de social networks y enfatizándo en el ownership de tu contenido.

**Comment by jjdelc** [comment]
Cuanto tiempo debe durar la charla?

**Comment by AngelFQC** [comment]
> Cuanto tiempo debe durar la charla?

20 o 30 minutos, está bien. Pero ya nos hemos pasado de tiempo, con demos y preguntas.
