### ISSUE TITLE
Hola Rust! Aprendiendo con rustlings

### ISSUE THREAD

**Issue by lupomontero** [mozillaperu/meetups#19]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación | Yo 
| Tipo de presentación       | Keynote

¡Hola!

Mi nombre es Lupo Montero, trabajo en @Laboratoria. Me pueden contactar por [acá](https://twitter.com/lupomontero).

**Título de la charla**

Hola Rust! Aprendiendo con `rustlings` :heart:🦀

**Descripción de la charla**

En esta charla veremo como empezar a leer y escribir Rust desde cero. Durante la charla haremos algunos ejercicios de [`rustlings`](https://github.com/rust-lang/rustlings) juntxs, y después cada unx puede continuar por su cuenta :wink: 

![crab pet](http://i.imgur.com/LbZJgmm.gif)

**Comment by AngelFQC** [comment]
Enlaces de ayuda
- https://dev.to/mattdark/primeros-pasos-con-rust-y-porque-aprenderlo-1oc3
- https://www.youtube.com/watch?v=xx8qiGMaLzo

**Comment by lupomontero** [comment]
Esta charla ya está agendada para esta noche, así que creo que podemos ir cerrando este issue...
