### ISSUE TITLE
Tecnología e Innovación Social

### ISSUE THREAD

**Issue by JorgeKtch** [mozillaperu/meetups#2]
¡Hola!

Mi nombre es Jorge

Soy fundador de CodeHunters Lab (http://www.facebook.com/CodehuntersLab), un emprendimiento social que busca reducir la brecha tecnológica llevando laboratorios móviles a comunidades alejadas y desarrollando talleres lúdicos de programación para que niños y jóvenes de escasos recursos aprendan a programar creando tecnología de forma divertida y gratuita.

Me contactan por Facebook http://www.facebook.com/JorgeJesusKtch

**Tipo de presentación que quiero hacer**
- Keynote (20 a 30 minutos)

**Título de la charla**
'Tecnología e innovación social VS Brecha digital'

**Descripción de la charla**
Analizar la problemática de la brecha digital, y compartir experiencias como emprendedor social a cargo de CodeHunters Lab.

**Para dictar la charla, mi laptop necesita conector:**
- HDMI

> ¿Quieres agregar algo más?

**Comment by ccarruitero** [comment]
@JorgeKtch gracias por proponer esta charla. Suena interesante tu proyecto
