### ISSUE TITLE
Privacidad en aplicaciones de chat

### ISSUE THREAD

**Issue by jjdelc** [mozillaperu/meetups#20]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación | Yo
| Tipo de presentación       | Keynote

¡Hola!

Mi nombre es Jj Trabajo en Crunch. Me contactan por https://isgeek.net

**Título de la charla**
Privacidad en aplicaciones de chat

- Firefox privacy philosophy

**Descripción de la charla**
Busco hacer una comparativa en la privacidad que las aplicaciones más populares de chat proveen y que considerar al elegir una de ellas.

**Comment by AngelFQC** [comment]
Hola @jjdelc 
El de este mes lo haremos sobre programación en Rust. Puedes para el meetup de julio?

**Comment by jjdelc** [comment]
Si, claro!

**Comment by AngelFQC** [comment]
Hola @jjdelc nos vemos el miércoles!

**Comment by AngelFQC** [comment]
https://www.isgeek.net/talks/chatapps
