### ISSUE TITLE
Breve introducción a Rust

### ISSUE THREAD

**Issue by AngelFQC** [mozillaperu/meetups#21]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación | Yo
| Tipo de presentación       | Keynote

¡Hola!

Mi nombre es Angel Quiroz @AngelFQC . Trabajo en @beeznest. Me contactan por Twitter / Github

**Breve Introducción a Rust**

**Descripción de la charla**
¿Qué es Rust? ¿Qué es Cargo? ¿Cómo configurarlos? Sintaxis y conceptos.

**Comment by lupomontero** [comment]
Esta charla ya está agendada para esta noche, así que creo que podemos ir cerrando este issue...

**Comment by AngelFQC** [comment]
La charla estará basada en _A very brief intro to Rust_ de @rustbridge

https://github.com/mozillaperu/a-very-brief-intro-to-rust
