### ISSUE TITLE
WebAssembly and Rust

### ISSUE THREAD

**Issue by ccarruitero** [mozillaperu/meetups#22]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación | Yo
| Tipo de presentación       | Keynote

¡Hola!

Mi nombre es César Carruitero. Me contactan por [Twitter](https://twitter.com/ccarruitero) / [Github](https://github.com/ccarruitero)

**Título de la charla**
- WebAssembly and Rust

**Descripción de la charla**
Se pretende hacer una breve actualización a WebAssembly. Se mostrará como  ha ido evolucionando la tecnología, el js api, algunos features que se tienen planeados y  algunos ejemplos de como utilizarlo con Rust.

Si bien se mostrará ejemplos utilizando Rust, no es necesario conocer el lenguaje para la charla.

**Comment by AngelFQC** [comment]
https://ccarruitero.github.io/rustwasm-slides/
