### ISSUE TITLE
Tema: WebHint en Firefox DevTools

### ISSUE THREAD

**Issue by collectivecloudperu** [mozillaperu/meetups#26]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación | Yo 
| Tipo de presentación       | Keynote

¡Hola!

Mi nombre es Juan Ricardo Castro Lurita Trabajo en Desarrollo de Software. 
Me contactan por Facebook: https://www.facebook.com/juan.castrolurita

**WebHint en Firefox DevTools**

- Que es WebHint ?
- Como Funciona WebHint
- Características
- Como usar WebHint en Firefox DevTools
- Ejemplo de uso en vivo

**Descripción de la Charla**
Explicare sobre el funcionamiento de WebHint en Firefox DevTools, compartiendo conocimiento sobre varios aspectos de esta herramienta.

**Sobre Mí**
Soy Ingeniero de Software con mas de 15 años trabajando en la creación de Software. Tengo mi Blog en donde disfruto compartir conocimiento sobre muchos temas. 
Blog: www.nubecolectiva.com 

Saludos Cordiales

**Comment by AngelFQC** [comment]
Juan preparó este post en su blog sobre el tema
http://blog.nubecolectiva.com/aplicando-buenas-practicas-a-un-sitio-web-usando-webhint-en-firefox-devtools/
