### ISSUE TITLE
Inteligencia Artificial con demo en vivo

### ISSUE THREAD

**Issue by Oxicode** [mozillaperu/meetups#28]
| Pregunta                   | Respuesta
|----------------------------|----------
| Quién hará la presentación |  / Yo 
| Tipo de presentación       | Keynote 

¡Hola

Soy Oxicode, llevo en el mundo de la tecnología ya un buen tiempito, (empecé creo que a los 14 años), soy FullStack, programador de Hobby, trabajo en UPC, donde veo proyectos de Inteligencia Artificial tanto de IBM (Watson) como de Azure (Microsoft). Ya perdí la cuenta a cuantas hackathons he ido.  🥇 

## ¿Cuál es el título de tu charla?
Demo de Inteligencia Artificial en reconocimiento de rostros

## Danos una descripción de tu charla (20 palabras)
Demostrar lo fácil de usar IA en modelos estándares, su integración con aplicaciones y jugar un rato con la IA.

## ¿Tienes alguna red social donde podamos contactarte?
http://linkedin.com/in/oxicode
http://fb.com/oxicode

## ¿Representas a alguna compañía o empresa?
Por ahora no

## ¿Quieres agregar algo más?
Conseguí un cupón por 100 dólares en consumo para Azure, en el evento al que más participe lo puedo dar ese cupón. Otra opción es sortearlo con la gente que asista.

**Comment by AngelFQC** [comment]
Hola @Oxicode tienes tu charla lista para el meetup del 28/11?

**Comment by AngelFQC** [comment]
ping @Oxicode
