### ISSUE TITLE
Propuesta de charla: Primeros pasos con WebAssembly y Rust

### ISSUE THREAD

**Issue by lupomontero** [mozillaperu/meetups#3]
¡Hola!

Mi nombre es Lupo Montero

Trabajo en [Laboratoria](https://www.laboratoria.la/)

Me contactan por [Twitter](https://twitter.com/lupomontero) / [Github](https://github.com/lupomontero)

**Tipo de presentación que quiero hacer**

- Keynote (20 a 30 minutos)

**Título de la charla**

* _Primeros pasos con WebAssembly y Rust_

**Descripción de la charla**

Una breve intro a WebAssembly y un ejemplo práctico implementando funcionalidad con Rust, compilando a Wasm y usando el resultado en el navegador.

**Para dictar la charla, mi laptop necesita conector:**

- HDMI

**Comment by ccarruitero** [comment]
@lupomontero suena genial lo de WebAssembly.

No estoy seguro cual es la otra propuesta que tenias en duda?
