### ISSUE TITLE
Tema: Mozilla Firefox y su soporte para el protocolo HTTP 3

### ISSUE THREAD

**Issue by collectivecloudperu** [mozillaperu/meetups#34]
¡Hola!

Mi nombre es Juan Castro.

**Me contactan por:**
[Facebook](https://www.facebook.com/CollectiveCloudPeru)
[Twitter](https://twitter.com/collectivecperu)
[Instagram](https://www.instagram.com/nube.colectiva/)

**Título de la charla:**
Mozilla Firefox y su soporte para el protocolo HTTP 3

**Tipo de presentación que quiero hacer:**
Keynote (20 a 30 minutos)

**Descripción de la charla:**
En esta Charla voy a compartir:

- El estado actual del protocolo HTTP 3 en Internet. 
- El estado actual del protocolo HTTP 3 en Mozilla Firefox. 
- Que cosas mejora este protocolo a Mozilla Firefox
- Características del Protocolo HTTP 3.
- Otros detalles.

**Comment by ccarruitero** [comment]
Hola @collectivecloudperu , gracias por tu propuesta de charla.

Podrias actualizar un poco la descripción de tu charla?

La descripción deberia poder darnos una idea sobre el tema y de que manera se planea abarcar el mismo durante la charla.

Además, que recuerde, hasta el momento no hemos tenido ninguna charla sobre HTTP3.

**Comment by collectivecloudperu** [comment]
> Hola @collectivecloudperu , gracias por tu propuesta de charla.
> 
> Podrias actualizar un poco la descripción de tu charla?
> 
> La descripción deberia poder darnos una idea sobre el tema y de que manera se planea abarcar el mismo durante la charla.
> 
> Además, que recuerde, hasta el momento no hemos tenido ninguna charla sobre HTTP3.

Perdón había olvidado actualiza la descripción de la charla. Ya la actualice !
