### ISSUE TITLE
Introducción a Web of Things

### ISSUE THREAD

**Issue by ccarruitero** [mozillaperu/meetups#5]
¡Hola!

Mi nombre es ...

Trabajo en ... (opcional incluir el nombre)

Me contactan por (Twitter / Github / Facebook)

**Tipo de presentación que quiero hacer**
- [ ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de la comunidad / actividades / etc.

**Título de la charla**
- Introduction to Web of Things (WoT)

**Descripción de la charla**
Explicar un poco el concepto de WoT, además realizar un pequeño demo con Mozilla Things Gateway.

**Para dictar la charla, mi laptop necesita conector:**
- [ ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

> ¿Quieres agregar algo más?

**Comment by AngelFQC** [comment]
Tomada en #15
